language: php

sudo: required

cache:
    directories:
        - "$HOME/.composer/cache"
        - "vendor"

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.1
          env: deps=low
        - php: 7.1
        - php: 7.2
        - php: nightly

before_script:
    - composer self-update
    - mkdir -p build/logs
    - mkdir -p build/cov
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - ./vendor/bin/phpunit -c phpunit-libraries.xml.dist --coverage-php build/cov/coverage-libraries.cov
    - ./vendor/bin/phpunit -c phpunit-symfony-bundle.xml.dist --coverage-php build/cov/coverage-symfony-bundle.cov
    - ./vendor/bin/phpunit -c phpunit-symfony-security-bundle.xml.dist --coverage-php build/cov/coverage-symfony-security-bundle.cov

after_success:
    - ./vendor/bin/phpcov merge --clover build/logs/clover.xml build/cov
    - ./vendor/bin/php-coveralls --no-interaction

after:
    - ./vendor/bin/phpstan analyze --level max -c phpstan.neon src
